
Description: >
    User Resource example
#  by wolfgang unger 9.3.2018

Resources:
  JenkinsUser:
    Type: 'AWS::IAM::User'
    Properties:
        UserName: Jenkins    
        Path: "/"
        LoginProfile:
            Password: jenKins12345!        
        Policies:
            - PolicyName: AmazonSSMFullAccess
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                        - 'cloudwatch:PutMetricData'
                        - 'ds:CreateComputer'
                        - 'ds:DescribeDirectories'
                        - 'ec2:DescribeInstanceStatus'
                        - 'logs:*'
                        - 'ssm:*'
                        - 'ec2messages:*'
                    Resource: '*'






