
Description: >
    env variables example
#  by wolfgang unger 9.3.2018
######################################################################################
#  Parameters
######################################################################################

Parameters: 

    #EnvironmentName:
    #    Description: An environment name that will be prefixed to resource names
    #    Type: String
    #    Default: env-variables

     # variables from the systems manager parameter store    
    EnvironmentVariable1:
        Description: Please enter Environment Variable 1
        Type: 'AWS::SSM::Parameter::Value<String>'
        Default: ungerw-parameter1
        

######################################################################################
#  Resources
######################################################################################

Resources:

  MasterStorage:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      FileSystemTags:
      - Key: Name
        Value: !Ref EnvironmentVariable1
      PerformanceMode: generalPurpose


#####################################################################################
#  Outputs
######################################################################################

Outputs:

    MasterStorage:
        Description: A reference to the MasterStorage
        Value: !Ref MasterStorage
        Export:
            Name: !Sub '${AWS::StackName}-FileSystem'


    