######################################################################################
#  Description
######################################################################################

Description: >
    docker ecs test (tomcat image) - tomcat image with port 8080
#  by wolfgang unger 9.3.2018


######################################################################################
#  Resources
######################################################################################

Resources:
    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: sinatra
            NetworkMode: awsvpc
            #NetworkMode: bridge
            # ExecutionRoleArn: todo # Role of ECS Cluster for excuting the services
            # TaskRoleArn: todo # Role for granting access for services like S3, DynamoDB...
            ContainerDefinitions:
                - Name: sinatra
                  Essential: true
                  Image: 'tongueroo/sinatra:latest'
                  Memory: 128
                  Command: 
                    - ruby
                    - hi.rb
                  PortMappings:
                    - ContainerPort: 4567
                      Protocol: tcp              
                  LogConfiguration:
                    LogDriver: awslogs
                    Options:
                        awslogs-group: !Ref AWS::StackName
                        awslogs-region: !Ref AWS::Region



