######################################################################################
#  Description
######################################################################################

Description: >
    This is a simple task definition example - bridge network mode
    
# by wolfgang unger 3.2018
######################################################################################
#  Parameters
######################################################################################
Parameters: 

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: ungerwHelloWorld-td-bridge

######################################################################################
#  Resources
######################################################################################

Resources:

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: !Sub '${EnvironmentName}'
            NetworkMode: bridge
            ContainerDefinitions:
                - Name: !Sub '${EnvironmentName}'
                  Essential: true
                  Image: strm/helloworld-http
                  Memory: 128
                  PortMappings:
                    - ContainerPort: 80
                  LogConfiguration:
                    LogDriver: awslogs
                    Options:
                        awslogs-group: !Ref AWS::StackName
                        awslogs-region: !Ref AWS::Region

    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 1 