######################################################################################
#  Description
######################################################################################

Description: >
    docker ecs test (tomcat image) - tomcat image with port 8080
#  by wolfgang unger 9.3.2018


######################################################################################
#  Resources
######################################################################################

Resources:
    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: tomcat
            NetworkMode: awsvpc
            #NetworkMode: bridge
            # ExecutionRoleArn: todo # Role of ECS Cluster for excuting the services
            # TaskRoleArn: todo # Role for granting access for services like S3, DynamoDB...
            ContainerDefinitions:
                - Name: tomcat
                  Essential: true
                  Image: 016973021151.dkr.ecr.eu-west-2.amazonaws.com/ungerw:tomcat.8.0
                  Memory: 128
                  PortMappings:
                    - ContainerPort: 8080
                      HostPort: 8080
                      Protocol: tcp
                    - ContainerPort: 80
                      HostPort: 80
                      Protocol: tcp                    
                  LogConfiguration:
                    LogDriver: awslogs
                    Options:
                        awslogs-group: !Ref AWS::StackName
                        awslogs-region: !Ref AWS::Region

    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 1 