######################################################################################
#  Description
######################################################################################

Description: >
    This is a simple hello world example - 
    
# by wolfgang unger 3.2018
######################################################################################
#  Parameters
######################################################################################


######################################################################################
#  Resources
######################################################################################

Resources:

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: hello-world
            NetworkMode: awsvpc
            ContainerDefinitions:
                - Name: hello-world
                  Essential: true
                  Image: strm/helloworld-http
                  Memory: 128
                  PortMappings:
                    - ContainerPort: 80
                  LogConfiguration:
                    LogDriver: awslogs
                    Options:
                        awslogs-group: !Ref AWS::StackName
                        awslogs-region: !Ref AWS::Region

    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 1 