######################################################################################
#  Description
######################################################################################

Description: >
    TargetGroup
# by Wolfgang Unger 3.2018
######################################################################################
#  Parameters
######################################################################################

Parameters: 

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: ungerwTG

    ParentVPCStack:
        Description: Please enter the Parent VPC Stack (do not change)
        Type: String
        Default: UngerwVPC




######################################################################################
#  Resources
######################################################################################

Resources:
    TargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Sub '${EnvironmentName}'
            VpcId:
                'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
            Port: 80
            Protocol: HTTP
            Matcher: 
                HttpCode: 200-299
            HealthCheckIntervalSeconds: 10
            HealthCheckPath: /
            HealthCheckProtocol: HTTP
            HealthCheckTimeoutSeconds: 5
            HealthyThresholdCount: 2
            #TargetType: ip
    