######################################################################################
#  Description
######################################################################################

Description: >
    service Role example
# by wolfgang unger 3.2018
######################################################################################
#  Parameters
######################################################################################

Parameters: 

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: ungerwECSServiceRole


######################################################################################
#  Resources
######################################################################################

Resources:

    ######################################################################################
    #  IAM Roles
    ######################################################################################
    # This IAM Role grants the service access to register/unregister with the 
    # Application Load Balancer (ALB). It is based on the default documented here:
    # http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_IAM_role.html

   
    ServiceRole:
     Type: 'AWS::IAM::Role'
     Properties:
      RoleName: !Sub '${EnvironmentName}'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AmazonEC2ContainerServiceRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:AuthorizeSecurityGroupIngress'
                  - 'ec2:Describe*'
                  - 'elasticloadbalancing:DeregisterInstancesFromLoadBalancer'
                  - 'elasticloadbalancing:DeregisterTargets'
                  - 'elasticloadbalancing:Describe*'
                  - 'elasticloadbalancing:RegisterInstancesWithLoadBalancer'
                  - 'elasticloadbalancing:RegisterTargets'
                Resource: '*'   

 
#####################################################################################
#  Outputs
######################################################################################

Outputs:

    ServiceRole:
        Description: Service Role for ECS Services 
        Value: !Ref ServiceRole
        Export:
            Name:  !Sub '${EnvironmentName}'