AWSTemplateFormatVersion: 2010-09-09

######################################################################################
#  Description
######################################################################################
Description: >-
  Template creates a Network Load Balancer 
  
# wolfgang unger 23.3.2018  
Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: NLB
        
  ParentVPCStack:
     Description: Please enter the Parent VPC Stack (do not change)
     Type: String
     Default: UngerwVPC

Resources:
      
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Type: network
      IpAddressType: ipv4
      Subnets: !Split
            - ','
            - 'Fn::ImportValue':
                !Sub '${ParentVPCStack}-PrivateSubnets'

      
  DefaultTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Sub ${EnvironmentName}-default
            #VpcId: !Ref ParentVPCStack
            VpcId:
                'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
            Port: 80
            #Protocol: HTTP  
            Protocol: TCP              
            

  LoadBalancerListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref LoadBalancer
            Port: 80
            #Protocol: HTTP
            Protocol: TCP            
            DefaultActions: 
                - Type: forward
                  TargetGroupArn: !Ref DefaultTargetGroup
    
