#####################################################################################
#  Description
######################################################################################

Description: >
    vgarage task definition - bridge network mode
    
# by wolfgang unger 4.2018
######################################################################################
#  Parameters
######################################################################################
Parameters: 

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: VGarage-TD

######################################################################################
#  Resources
######################################################################################

Resources:

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: !Sub '${EnvironmentName}'
            NetworkMode: bridge
            ContainerDefinitions:
                - Name: !Sub '${EnvironmentName}'
                  Essential: true
                  Image: 431271371214.dkr.ecr.eu-central-1.amazonaws.com/ecs-repository:man-ms-virtualgarage_0.0.1-SNAPSHOT
                  Memory: 700
                  Environment:
                    - Name: SPRING_PROFILES_ACTIVE
                      Value: cloudint
                    - Name: MONGO_DB_HOST
                      Value: man_vgarage_db_mongo                 
                  PortMappings:
                    - ContainerPort: 8085
                      HostPort: 8085
                      Protocol: tcp
                  Links:
                    - man_vgarage_db_mongo                      
                  LogConfiguration:
                    LogDriver: awslogs
                    Options:
                        awslogs-group: !Ref AWS::StackName
                        awslogs-region: !Ref AWS::Region
                        
                - Name: man_vgarage_db_mongo
                  Essential: true
                  Image: tutum/mongodb:3.2
                  Memory: 500
                  Environment: 
                    - Name: MONGODB_USER
                      Value: garage
                    - Name: MONGODB_PASS
                      Value: xohGe6nu.cieG7aaJ
                    - Name: MONGODB_DATABASE
                      Value: garagedb
                  #PortMappings:
                  #  - ContainerPort: 27017
                  #    HostPort: 27017
                  #    Protocol: tcp
                  LogConfiguration:
                      LogDriver: awslogs
                      Options:
                        awslogs-group: !Ref AWS::StackName
                        awslogs-region: !Ref AWS::Region                  

    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 1 