---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cognito PreSignin Lambda'

Parameters:
 LambdaRoleArn:
  Description: The role arn to execute the lambda_function
  Type: String
  Default: arn:aws:iam::016973021151:role/service-role/LambdaRole

Resources:
  Lambda1:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
            ZipFile: >
                import base64
                
                def lambda_handler(event, context):
                    event['response'] = {
                    "autoConfirmUser": True
                    }
                    return event
        Description: Cognito PreSignin Script
        FunctionName: CognitoPreSigninCF
        Handler: index.lambda_handler
        Role: !Ref LambdaRoleArn
        Runtime: python2.7

